### ISSUE TITLE
GTUltra exports stereo .sng files even when using only mono

### ISSUE THREAD

**Issue by DeMOSic** [jpage8580/GTUltra#11]
So take this module for example, done in goattracker ultra. this is supposed to be 1sid BUT GTUltra exports GoatTracker Stereo sngs even if your track is set as 1sid.

https://csdb.dk/getinternalfile.php/227158/Powered_by_Drum_Patterns.sng

**Comment by jpage8580** [comment]
Hmm.. fix one thing. Break another. Will take a look….

**Comment by jpage8580** [comment]
Is this using the latest V1.1.0 version? I'm sure it's playing as mono here when I exported with SIDs set to 1.

I've attached the exported .sid file

[Powered_by_Drum_Patterns.zip](https://github.com/jpage8580/GTUltra/files/8402330/Powered_by_Drum_Patterns.zip)

**Comment by DeMOSic** [comment]
i dont mean the sid. i mean the sng

**Comment by jpage8580** [comment]
Ah. In that case, yes, you're right. It saves in the exact same .sng format as GTStereo. I thought it would be very dangerous to save, based on the number of SIDs selected, as you could accidently save a 6 channel SID as 3, and lose all a lot of work.

I presume you'd want to save as 3 channel sng, so that you could then load it back into the original GT editor? If I understand the use case, I'll think about how best to incorporate it.

Cheers

**Comment by jpage8580** [comment]
And, just to confirm that I'm understanding correctly - it EXPORTS to 3 channel sid OK.. It just doesn't SAVE as a 3 channel .sng?

**Comment by DeMOSic** [comment]
yeah, thats right. maybe make a feature to be able to select what typa sng to save. maybe do it in the config like

; Ask if want to export to 3ch or 6ch sng before export (0 = OFF 1 = ON)
0

**Comment by jpage8580** [comment]
I’ll likely put a tickbox and a warning in the save screen. I’ve added it to my to-do list. Lovely track, by the way!

**Comment by DeMOSic** [comment]
Thanks! Mega Sparky made it, not me

**Comment by jpage8580** [comment]
Latest version V1.1.1 will automatically save as original 3 channel sng file if it detects either no patterns in the order list for channels 3-6 or if the patterns in the order list for channels 3-6 are all empty
