### ISSUE TITLE
weird bug

### ISSUE THREAD

**Issue by DeMOSic** [jpage8580/GTUltra#16]
notes dont look correct
![image](https://user-images.githubusercontent.com/82211203/162561078-170d1f4d-ce7b-48dd-b232-aee94f50995c.png)

**Comment by jpage8580** [comment]
Ouch. Corrupt data

Can you send me the .sng file that does this?

**Comment by jpage8580** [comment]
(Original title summed it up better ;-) )

**Comment by jpage8580** [comment]
I’ve got the file link via DM. Will take a look. Thanks

**Comment by DeMOSic** [comment]
Sent it to you on FaceBook. changed name of issue thing cuz i thought because i put fuck in it it wouldnt send lmao

**Comment by jpage8580** [comment]
Works here OK with the latest V1.1.2 release
Can you try downloading that and see if the problem still persists?

**Comment by jpage8580** [comment]
This was fixed by deleting the GTUltra.cfg file.
GTStereo has a bug when handling strings in the config file. Luckily, there's only strings (file path info) at the end of the config file, so this was never a problem..

The bug results in corrupt information for the scalatuningfilepath and specialnotenames config params, ending in the weird note display.

As I've added more options since, this initially caused the saved .cfg file to have corrupted info.
I've fixed that bug, so hopefully you won't see this problem again
