### ISSUE TITLE
Packer/relocator sometimes says "OUT OF MEMORY IN PACKER/RELOCATOR" and crashes the program

### ISSUE THREAD

**Issue by acrouzet** [jpage8580/GTUltra#32]

**Comment by jpage8580** [comment]
Always with the same .sng ? How many channels? Need more details.

**Comment by acrouzet** [comment]
[89.zip](https://github.com/jpage8580/GTUltra/files/8983835/89.zip)
It's this .sng

**Comment by jpage8580** [comment]
I can't repro. I've modified the code to hopefully give more info as to where this is happening (that same text output is displayed in 3 places when allocating memory for song, pattern and instrument data).

**Comment by acrouzet** [comment]
![image](https://user-images.githubusercontent.com/47704566/175797199-068ec8b4-6a42-4141-a263-155338c45e35.png)
This is the error I got.

**Comment by jpage8580** [comment]
When did this start happening? Since this branch version?
That size looks correct, which makes me think you are actually just out of
memory. Does this happen as soon as you load the sng, or only after some
time where you’ve edited the music?

I’ll add output to show available memory to the branch version. I couldn’t
see this falling in my local version, so I don’t think there’s a memory
leak.

**Comment by jpage8580** [comment]
Just pushed another version that displays the available memory. Click on the record button to update it (checking constantly for available memory has the side-effect of reducing available memory over time due to fragmentation. )
Would be good to know if you're seeing a sudden drop during use for some reason, or if you're just starting off with a low amount.
Only major change that I can think of is the change to screen size for this version. But considering what apps and games can do on a regular Windows PC today, I'd be surprised if that's causing the problem. I'm showing. I'm showing around 1.5gb of free RAM (app is win32, so I malloc would be limited to 4GB anyway, AFAIK)

**Comment by acrouzet** [comment]
> Just pushed another version that displays the available memory. Click on the record button to update it (checking constantly for available memory has the side-effect of reducing available memory over time due to fragmentation. ) Would be good to know if you're seeing a sudden drop during use for some reason, or if you're just starting off with a low amount. Only major change that I can think of is the change to screen size for this version. But considering what apps and games can do on a regular Windows PC today, I'd be surprised if that's causing the problem. I'm showing around 1.5gb of free RAM (app is win32, so I malloc would be limited to 4GB anyway, AFAIK)

![image](https://user-images.githubusercontent.com/47704566/176250864-4988fd38-209e-41fe-80e5-824419b6d0b5.png)
This number doesn't change and yet I'm still getting the error message when trying to pack the same tune.

**Comment by jpage8580** [comment]
Still can't replicate. Can you send me your gtultra.cfg file

**Comment by acrouzet** [comment]
[gtultra.zip](https://github.com/jpage8580/GTUltra/files/9013529/gtultra.zip)

**Comment by jpage8580** [comment]
Still no luck in getting this to repro :-(
I've pushed another version to the New-OrderList-View branch that displays more info when you pack (available memory / required memory that will be allocated).. I'd expect there to be a massive decrease in available memory prior to you getting the OUT OF MEMORY error. But I can't see why or how it gets into that situation.

My steps to try to repro:
- Load 89.sng
- Set SIDs to 2 in the transport bar
- F9... and accept the default settings.

Please let me know if you're doing anything differently

**Comment by acrouzet** [comment]
I have the number of SIDs set to 1 in the transport bar. I've also noticed that the memory error doesn't occur with a 2SID project I'm working on.

**Comment by jpage8580** [comment]
Still can't repro. Let me know if the the free memory / allocated sizes in the latest branch version show anything unusual

**Comment by acrouzet** [comment]
Okay, so now the .sng seems to export without issue...
